name: flutter_check_box_rounded_example
description: A example check box rounded flutter project.
version: 1.0.0+1

publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_check_box_rounded:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
