name: flutter_check_box_rounded

description: Package created to give a fully functional and customizable rounded checkbox.

version: 3.3.0

homepage: https://github.com/ziqq/flutter_check_box_rounded

repository: https://github.com/ziqq/flutter_check_box_rounded

issue_tracker: https://github.com/ziqq/flutter_check_box_rounded/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://www.patreon.com/ziqq
  - https://boosty.to/ziqq

platforms:
  android:
  ios:

#screenshots:
#  - description: 'Example of using the library to check app version.'
#    path: example.png

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
