name: flutter_check_box_rounded

description: Package created to give a fully functional and customizable rounded checkbox.

version: 3.2.3

homepage: https://github.com/ziqq/flutter_check_box_rounded

repository: https://github.com/ziqq/flutter_check_box_rounded

issue_tracker: https://github.com/ziqq/flutter_check_box_rounded/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: ^1.24.2

  flutter_lint_rules:
    git:
      url: https://github.com/ziqq/flutter_lint_rules.git
      ref: main


flutter:
