name: flutter_check_box_rounded
description: Package created to give a fully functional and customizable rounded checkbox.
homepage: https://github.com/ziqq/flutter_check_box_rounded
version: 3.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lint_rules:
    git:
      url: https://github.com/ziqq/flutter_lint_rules.git
      ref: main

flutter:
