name: "Analysis And Tests"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    uses: ziqq/flutter_ci_workflows/.github/workflows/analysis.yml@main
  tests:
    uses: ziqq/flutter_ci_workflows/.github/workflows/testing.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}