name: "CheckBoxRounded"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    uses: ziqq/flutter_ci_workflows/.github/workflows/analysis.yml@main